const BISAC = [
    "Biography",
    "Body, Mind & Spirit",
    "Business & Economics",
    "Comics & Graphic novel",
    "Cooking",
    "Crafts & Hobbies",
    "Design",
    "Drama",
    "Education",
    "Family & Relationships",
    "Fiction",
    "Foreign language study",
    "Health & Fitness",
    "History",
    "Law",
    "Mathematics",
    "Medical",
    "Music",
    "Nature",
    "Science",
    "Self-help",
    "Sports & Recreation",
    "Technology & engineering",
    "Travel"
]